// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Start here for orientation and project selection.',
      },
      items: [{type: 'autogenerated', dirName: 'basics'}],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Guides',
        description: 'Step-by-step setup and workflow guides.',
      },
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Projects',
      link: {
        type: 'generated-index',
        title: 'Projects',
        description: 'Build documentation for complete Mechaxil projects.',
      },
      items: [
        // {
        //   type: 'category',
        //   label: 'Solar',
        //   link: {type: 'doc', id: 'projects/solar/overview'},
        //   items: [
        //     'projects/solar/bom',
        //     'projects/solar/schematics',
        //     'projects/solar/wiring',
        //     'projects/solar/testing',
        //     'projects/solar/firmware',
        //   ],
        // },
        {
          type: 'category',
          label: 'Smart Watering Pot',
          link: {type: 'doc', id: 'projects/smart-auto-watering-pot/docs/auto-watering-pot'},
          items: [
            'projects/smart-auto-watering-pot/docs/auto-watering-pot-bom',
            'projects/smart-auto-watering-pot/docs/auto-watering-pot-schematics',
            'projects/smart-auto-watering-pot/docs/auto-watering-pot-calibration',
            'projects/smart-auto-watering-pot/docs/auto-watering-pot-firmware',
            'projects/smart-auto-watering-pot/docs/auto-watering-pot-deployment',
            'projects/smart-auto-watering-pot/docs/auto-watering-pot-conclusion',
          ],
        },
        // 'projects/under_development',
      ],
    },
    {
      type: 'category',
      label: 'Products',
      link: {
        type: 'generated-index',
        title: 'Products',
        description: 'Boards, modules, kits, and hardware platforms.',
      },
      items: [
        'products/rp2040-pico-w',
        'products/D4184',
        {
          type: 'category',
          label: 'Pico I/O Board',
          link: {type: 'doc', id: 'products/pico-io-board/pico-io-board'},
          items: [
            'products/pico-io-board/pico-io-board-mechanical',
            'products/pico-io-board/pico-io-board-assembly',
            'products/pico-io-board/pico-io-board-electrical',
            'products/pico-io-board/pico-io-board-manufacturing',
            'products/pico-io-board/pico-io-board-firmware',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Protocols',
      link: {
        type: 'generated-index',
        title: 'Mechaxil Protocols',
        description: 'Reference pages for supported protocols, including pinouts, wiring diagrams, and configuration guides.',
      },
      items: [{type: 'autogenerated', dirName: 'protocols'}],
    },
  ],
};

module.exports = sidebars;
